### ISSUE TITLE
Test suite length

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#163]
Just leaving here a note of a discussion that I had with @thomasgibson so that hopefully we'll remember to do this!

We were thinking that the two of us would go through the tests and examples at some point to try to reduce the time that it takes the run the whole suite (e.g. by reducing the resolutions of each test)

**Comment by jshipton** [comment]
I was thinking about restructuring the tests, especially the testing of the examples. At the moment we run each example for one timestep, just to check that everything is set up correctly. I don't think this is necessary for tests that are very similar - e.g. the 6 shallow water tests. I had a couple of thought on how to improve things:

1. We could have separate directories under the examples directory for the different models (shallow water, slice tests, dcmip tests etc.) and just test one in each subdirectory
2. Since the majority of each setup file is very similar, we could reduce the number of files and use command line options to set up different problems - then we could just use one option when testing (e.g. the shallow water tests could be condensed to 1 file with an input option to decide whether to run Williamson 2, 5, 6 or Galewsky and when testing, just do Williamson 2)
3. Some examples can be deleted or have the options they test moved into an actual test.

Shall I start a branch for this?

**Comment by tommbendall** [comment]
This is being addressed by #252 so this can be closed
