### ISSUE TITLE
parallel problem when creating output directory

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#40]
I really love not overwriting results by accident but the check on line 123 of state.py does not seem to be very parallel friendly as if fails on some processors sometimes when running in parallel. @wence- is there a parallel-friendly way to do this?

**Comment by wence-** [comment]
For context, I've copied the appropriate bit of code:

```python
        self.dumpdir = path.join("results", self.output.dirname)
        outfile = path.join(self.dumpdir, "field_output.pvd")
        if self.dumpfile is None:
            if path.exists(self.dumpdir):
                exit("results directory '%s' already exists" % self.dumpdir)
            self.dumpcount = itertools.count()
            self.dumpfile = File(outfile, project_output=self.output.project_fields)
            self.diagnostic_data = defaultdict(partial(defaultdict, list))
```

The problem here is a race condition on the creation of `dumpdir`.  The `File` object has code:

```python
        if comm.rank == 0:
            outdir = os.path.dirname(os.path.abspath(filename))
            if not os.path.exists(outdir):
                os.makedirs(outdir)
        comm.barrier()
```

So there is a barrier after creating the directory to ensure that all processes see it.

However, what is likely happening in parallel for you is that rank 0 gets past the check for whether the directory exists and goes ahead and creates the file.  Then rank 1 arrives at the check, notices it already exists, and exits.

I think it is safe to guard the check for an existing directory on rank 0.

```python
if comm.rank == 0 and path.exists(...):
    exit(...)
```

That could just be `COMM_WORLD` if you like.

**Comment by jshipton** [comment]
Yes, that sounds like exactly what is happening - only some of the time though which is what confused me! Thanks for the fix.

________________________________

**Comment by jshipton** [comment]
Is there a better way of getting comm? When I run the vertical slice code in parallel (e.g. dense_bubble.py example on branch slice_EP) I get the following error:
AttributeError: 'ExtrudedMeshTopology' object has no attribute 'comm'
    return getattr(self._topology, name)

**Comment by wence-** [comment]
This doesn't occur for me.  Are you sure your firedrake is up to date?  I note in passing that the dense bubble example doesn't run at all since it was modified to run at a range of resolutions (various variables are undefined).

**Comment by jshipton** [comment]
It doesn't always occur for me either.

________________________________

**Comment by jshipton** [comment]
Oh, hang on, different issue. Let me check...
