### ISSUE TITLE
Rework field creation/initialisation

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/gusto#68]
Debugging the problem of picking up from checkpoints with Colin yesterday we found the problem: the background fields were not correctly being initialised on pickup.  Part of the reason for this is that the way the code currently works, it's not clear when creating fields and then shoving them back into the state object whether a reference is taken or a copy made.

The current pseudo-code is something like:

```python
state = ...
W = state.build_spaces()
field = Function(W)
state.set_field("field", field)
state.set_reference_profiles(field)
state.output.meanfields['...'] = state
```

It turned out that `set_reference_profiles` projected the input field into internal variables, but the dump output just contained the originals.  So then later when picking up from a dump, the mean fields were picked up, but not referenced inside the state object correctly.

How to improve this?  Here is one suggestion, I don't know if it's the best option.

There are two "types" of field, I think.  Temporaries, that the state and timeloop creates internally, (the user never touches these), for example the intermediate stages of the RK scheme.  And "named" fields, for example the initial conditions, the background profiles, the solution, etc...

At the moment we make the named fields by hand, then push them into the state object and have to remember to get the out in the right place and so on.  But these are just fields that the state object can make and should know about.  So how about referring to them by name.

```python

rhobar = state.create_named_field(space, "rhobar")
...

# Then inside state:

state.get_named_field("rhobar")
```

Better names are obviously available.

Thoughts?

**Comment by jshipton** [comment]
So is the idea that state should do all the creation of fields? I'd be interested to see which file failed the checkpointing, just because I'm a bit confused as all the examples files that I have used pass state.rhobar (or whatever) to state.output.meanfields, not the rhobar function created by the user - does that get around the problem? Even if it does, I still prefer that state creates all the fields (and am going to write that code now) but I want to check that I understand the problem.

**Comment by jshipton** [comment]
In fact, doesn't the current version of state_restructure fix this (at least for the checkpointing issue caused by the reference profiles)? I've written a method called set_reference_profiles which takes in a dictionary of the form {name: profile} where name is the name of the field for which this is the reference profile, and profile is a function. The method then creates a function on the same space as the field, projects the input function to this function and puts it in a dictionary state.ref

**Comment by wence-** [comment]
Can you point me at some code?  Colin maybe has the example that was breaking.

The problem was the following sequence of events:

```python
state.initialise([u0, rho0, theta0])
state.set_reference_profiles(rho_b, theta_b)
state.output.meanfields = {'rho': rho_b, 'theta':theta_b}
```

Where `set_reference_profiles` projects into some internal fields.  So now we dump `rho_b` and `theta_b` correctly, but when picking up, we set the provided fields `rho_b` and `theta_b`, but never transfer to the state-internal `rhobar` and `thetabar`.  Moreover, it's unclear from the public API whether the reference profiles provided are referenced or not.

Now, the examples have been updated to do something like:

```python
state.initialise([u0, rho0, theta0])
state.set_reference_profiles(rho_b, theta_b)
state.output.meanfields = {'rho':state.rhobar, 'theta':state.thetabar}
```

So that would work.

But why all this shuffling with extra fields?  I was suggesting that internally, when the state object needs `rohbar` and `thetabar`, it should refer to them by name.  Then the user should be able to grab fields by name, and set values which are automatically the internal values.

Perhaps something sketched like this?

```python
class FieldCreator(object):

   def __call__(self, name, space):
       try:
            return getattr(self, name)
       except AttributeError:
           value = Function(space, name=name)
           setattr(self, name, value)
           return value

class State(object):
     def __init__(self, ...):
          self.fields = FieldCreator()


state = State(...)

rhobar = state.fields("rhobar", state.V[0])
rhobar.interpolate(...)
state.set_reference_profile("rhobar")
  -> can get the rhobar field with getattr(state.fields, "rhobar")
```

I admit I haven't thought super-hard about this.  But it seems to me it might be clearer than sometimes passing references, sometimes making copies, sometimes making projections etc...

**Comment by jshipton** [comment]
We have implemented something along these lines.
